theme: jekyll-theme-minimal
title: Legalize Nuclear Bombs
description: Recommend us!
url: "https://legalizenuclearbombs3.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
